### ISSUE TITLE
No encuentra los archivos o directorios que contengan espacios

### ISSUE THREAD

**Issue by sosacode20** [leismael/little_c_web_server#7]
Cuando el cliente le pide al web server algun archivo con espacios suelta incorrectamente un error **404** y esto es debido a que la peticion que recibe en el http es con "%20" para representar los espacios. Solo habria que reconocer el "%20" como el espacio a la hora de buscar el archivo o directorio @dfg-98

**Comment by dfg-98** [comment]
Fixed in 961161099ca672653c2612c880ee48c52f513135
